apiVersion: v1
kind: Service
metadata:
  name: flight-service
spec:
  selector:
    app: flight-service
  ports:
    - name: http
      protocol: TCP
      port: 8082   # This is the port you want to expose externally via NodePort
      targetPort: 8080  # This should be the port your application listens on within the pod
  type: NodePort # Use NodePort to make it accessible externally
