apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service-deployment
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
        - name: flight-service
          image: sweetyrv/flight_booking:flight-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_DATABASE
              value: flight_booking
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DB_HOST
              value: mysqldb
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb:3306/flight_booking?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
      # Add any necessary volume mounts or other configuration here
